name: deploy-cf-worker
on: 
  workflow_call:
    inputs:
      environment:
        description: "Choose environment"
        required: false
        default: 'prod'
        type: string
    secrets:
      CF_API_TOKEN:
        required: true

jobs:
  deploy-cf-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm install
      - name: Push to Workers
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          SECRETS: VERSION
          environment: ${{ github.event.inputs.environment }}
        env:
          VERSION: ${{ github.sha }}
