name: deploy-cf-worker
on: 
  workflow_call:
    secrets:
      CF_API_TOKEN:
        required: true

jobs:
  deploy-cf-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install
      - name: Push to Workers
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          SECRETS: VERSION
        env:
          VERSION: ${{ github.sha }}